name: Build and Test DeriSock Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore Packages
      run: |
        dotnet restore DeriSock
#        dotnet restore DeriSock.Tests
        
    - name: Build with dotnet
      run: |
        dotnet build --no-restore --configuration Release DeriSock
#        dotnet build --no-restore --configuration Release DeriSock.Tests

#    - name: Run Tests
#      run: dotnet test --no-restore DeriSock.Tests